# Generated by Django 2.2.4 on 2021-12-03 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoMantenimientoView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activo_id', models.IntegerField()),
                ('tipo', models.CharField(choices=[('D', 'Depósito'), ('V', 'Vehículo'), ('M', 'Material'), ('A', 'Documentación')], default='D', max_length=1)),
                ('activo', models.CharField(max_length=40)),
                ('mantenimiento_id', models.IntegerField()),
                ('mantenimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('estado', models.CharField(choices=[(None, '---'), ('R', 'No Cumple'), ('A', 'Atención'), ('V', 'Cumple')], default='V', max_length=1)),
                ('proximo', models.DateField(blank=True, null=True)),
                ('fecha_inicial', models.DateField(blank=True, null=True, verbose_name='Válido desde')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
            ],
            options={
                'db_table': 'activo_mantenimiento_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('tipo', models.CharField(choices=[('D', 'Depósito'), ('V', 'Vehículo'), ('M', 'Material'), ('A', 'Documentación')], default='D', max_length=1)),
                ('descripcion', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['tipo', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Diccionario_ART',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('diccionario', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Diccionario ART',
                'verbose_name_plural': 'Diccionarios ART',
            },
        ),
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=60, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=60)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('cuil', models.CharField(blank=True, max_length=13, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('fec_nac', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('descripcion', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rrhh.Persona')),
                ('legajo', models.CharField(max_length=4)),
                ('fec_ing', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('fec_egr', models.DateField(blank=True, null=True, verbose_name='Fecha Egreso')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='rrhh/empleados/')),
                ('tarea', models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Tarea')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['persona__apellido', 'persona__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripción')),
                ('estado', models.CharField(blank=True, choices=[(None, '---'), ('R', 'No Cumple'), ('A', 'Atención'), ('V', 'Cumple')], default='V', max_length=1, null=True)),
                ('proximo', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Próxima acción')),
                ('fecha_inicial', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha Inicial')),
                ('fecha_final', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha Final')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='rrhh/activos/')),
                ('activo', models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mantenimientos', to='rrhh.Activo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('fec_inicio', models.DateField(blank=True, verbose_name='Fecha Inicio')),
                ('fec_fin', models.DateField(blank=True, verbose_name='Fecha Fin')),
                ('fec_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha Solicitud')),
                ('periodo', models.SmallIntegerField(blank=True, null=True, verbose_name='Año')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('estado', models.CharField(blank=True, choices=[('A', 'Aprobada'), ('P', 'Pendiente'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('empleado', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Empleado')),
            ],
            options={
                'verbose_name': 'Vacación',
                'verbose_name_plural': 'Vacaciones',
                'ordering': ['empleado', 'periodo', 'fec_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('domicilio', models.CharField(max_length=90)),
                ('localidad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=30)),
                ('cp', models.CharField(max_length=12)),
                ('pais', models.CharField(max_length=30)),
                ('empleado', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Empleado')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
        migrations.CreateModel(
            name='DiasVacaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('periodo', models.SmallIntegerField(verbose_name='Año')),
                ('dias_vacaciones', models.SmallIntegerField(verbose_name='Días de vacaciones')),
                ('dias_disfrutados', models.SmallIntegerField(verbose_name='Días disfrutados')),
                ('dias_pendientes', models.SmallIntegerField(verbose_name='Días pendientes')),
                ('empleado', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Empleado')),
            ],
            options={
                'verbose_name': 'Dia de Vacación',
                'verbose_name_plural': 'Dias de Vacaciones',
                'ordering': ['empleado', 'periodo'],
            },
        ),
        migrations.CreateModel(
            name='Denuncia_ART',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('siniestro', models.IntegerField()),
                ('fec_siniestro', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha Siniestro')),
                ('fec_denuncia', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha Denuncia')),
                ('zona_afectada', models.TextField(blank=True, null=True, verbose_name='Zona Afectada')),
                ('estado', models.CharField(blank=True, choices=[('P', 'Pendiente'), ('A', 'Aceptado'), ('R', 'Rechazado')], default='P', max_length=1, null=True)),
                ('fec_alta_medica', models.DateField(blank=True, null=True, verbose_name='Fecha Alta')),
                ('motivo_alta', models.ForeignKey(blank=True, limit_choices_to={'diccionario': 'motivoAlta'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='motivo_alta_id', to='rrhh.Diccionario_ART', verbose_name='Motivo de Alta')),
                ('tipo_accidente', models.ForeignKey(blank=True, limit_choices_to={'diccionario': 'tipoAccidente'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_accidente_id', to='rrhh.Diccionario_ART', verbose_name='Tipo de Accidente')),
                ('tipologia', models.ForeignKey(blank=True, limit_choices_to={'diccionario': 'tipologia'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipologia_id', to='rrhh.Diccionario_ART')),
                ('empleado', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Empleado')),
            ],
            options={
                'verbose_name': 'Denuncia ART',
                'verbose_name_plural': 'Denuncias ART',
                'ordering': ['fec_siniestro'],
            },
        ),
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('tipo', models.CharField(choices=[('movil', 'Celular'), ('tel', 'Teléfono'), ('wa', 'WhatsApp'), ('sms', 'Mensaje SMS'), ('email', 'Correo Electrónico'), ('face', 'Facebook'), ('git', 'GitHub'), ('gmail', 'Google+'), ('link', 'LinkedIn'), ('pint', 'Pinterest'), ('twitt', 'Twitter'), ('ytube', 'YouTube')], default='movil', max_length=5)),
                ('texto', models.CharField(max_length=150)),
                ('empleado', models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Empleado')),
            ],
            options={
                'verbose_name': 'Comunicacion',
                'verbose_name_plural': 'Comunicaciones',
                'ordering': ['empleado', 'tipo', 'texto'],
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.Empleado'),
        ),
    ]
