# Generated by Django 2.2.1 on 2019-08-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('tipo', models.CharField(choices=[('movil', 'Celular'), ('tel', 'Teléfono'), ('wa', 'WhatsApp'), ('sms', 'Mensaje SMS'), ('email', 'Correo Electrónico'), ('face', 'Facebook'), ('git', 'GitHub'), ('google', 'Google+'), ('link', 'LinkedIn'), ('pinter', 'Pinterest'), ('twitt', 'Twitter')], default='movil', max_length=5)),
                ('texto', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Comunicacion',
                'verbose_name_plural': 'Comunicaciones',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('domicilio', models.CharField(max_length=90)),
                ('localidad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=30)),
                ('cp', models.CharField(max_length=12)),
                ('pais', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=60)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('cuil', models.CharField(blank=True, max_length=13, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('fec_nac', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Creado por')),
                ('modified', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado')),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Modif. por')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rrhh.Persona')),
                ('legajo', models.IntegerField()),
                ('fec_ing', models.DateField(blank=True, null=True)),
                ('fec_egr', models.DateField(blank=True, null=True)),
                ('comunicaciones', models.ManyToManyField(blank=True, related_name='empleado_comunicaciones', to='rrhh.Comunicacion')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['persona__apellido', 'persona__nombre'],
            },
        ),
    ]
