# Generated by Django 2.2.1 on 2019-08-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('tel', 'Teléfono'), ('movil', 'Celular'), ('wa', 'WhatsApp'), ('email', 'Correo Electrónico'), ('face', 'Facebook'), ('twitt', 'Twitter'), ('link', 'LinkedIn')], default='movil', max_length=5)),
                ('texto', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Comunicacion',
                'verbose_name_plural': 'Comunicaciones',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domicilio', models.CharField(max_length=90)),
                ('localidad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=30)),
                ('cp', models.CharField(max_length=12)),
                ('pais', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=60)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('cuil', models.CharField(blank=True, max_length=13, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('fec_nac', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('legajo', models.IntegerField()),
                ('fec_ing', models.DateTimeField(blank=True, null=True)),
                ('fec_egr', models.DateTimeField(blank=True, null=True)),
                ('comunicaciones', models.ManyToManyField(blank=True, related_name='empleado_comunicaciones', to='rrhh.Comunicacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Persona')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['persona__apellido', 'persona__nombre'],
            },
        ),
    ]
