# Generated by Django 2.2.1 on 2019-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacion',
            name='tipo',
            field=models.CharField(choices=[('movil', 'Celular'), ('tel', 'Teléfono'), ('wa', 'WhatsApp'), ('sms', 'Mensaje SMS'), ('email', 'Correo Electrónico'), ('face', 'Facebook'), ('git', 'GitHub'), ('google', 'Google+'), ('link', 'LinkedIn'), ('pinter', 'Pinterest'), ('twitt', 'Twitter')], default='movil', max_length=5),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fec_egr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fec_ing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fec_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
