# Generated by Django 2.2.4 on 2019-08-03 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('idactividad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Califica',
            fields=[
                ('idcalifica', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'califica',
            },
        ),
        migrations.CreateModel(
            name='Estadocliente',
            fields=[
                ('idestadocliente', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=40, null=True)),
                ('fechaalta', models.DateTimeField(blank=True, null=True)),
                ('datospc', models.CharField(blank=True, max_length=60, null=True)),
                ('idopera', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estadocliente',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('fantasia', models.CharField(blank=True, max_length=60, null=True)),
                ('direc_d', models.CharField(blank=True, max_length=60, null=True)),
                ('directivos', models.CharField(blank=True, max_length=60, null=True)),
                ('telef_d', models.CharField(blank=True, max_length=20, null=True)),
                ('email_d', models.CharField(blank=True, max_length=90, null=True)),
                ('idprovincias', models.CharField(blank=True, max_length=15, null=True)),
                ('localidad', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('actividad', models.ForeignKey(db_column='idactividad', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Actividades')),
                ('califica', models.ForeignKey(db_column='idcalifica', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Califica')),
                ('estadocliente', models.ForeignKey(db_column='idestadocliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Estadocliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
    ]
